#!/bin/sh
#--------------------------------------------------------------------------
# xinitrc_example
#		File executed by startx (run your window manager from here) that
#		should be copied as ~/.xinitrc for a X11 environment, preferably
#		on Linux or Unix systems.
#       Copyright (c) 2010-2016, Michael Paquier
#--------------------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Merge custom settings of xterm (note that this needs the package
# xorg-xrdb)
xrdb -merge ~/.xresources

# Disk automount
udiskie &

# Switch CAPS and ctrl on keyboard.
# Doing so has the disadvantage to not work for TTY sessions, But the
# advantage to not need a personal keymap and there is no need as well
# to update the system-wide /etc/vconsole.conf.
setxkbmap -option "ctrl:swapcaps"

# Settings for Japanese input
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS=@im='ibus'

# Then start the ibus daemon to control input
ibus-daemon -drx

# Disable bell sound
xset -b

# Execute i3 as window manager at startup
exec i3

# Execute awesome as window manager at startup
# exec awesome
