#!/bin/sh
#--------------------------------------------------------------------------
# xinitrc_example
#		File executed by startx (run your window manager from here) that
#		should be copied as ~/.xinitrc for a X11 environment, preferably
#		on Linux or Unix systems.
#       Copyright (c) 2010-2016, Michael Paquier
#--------------------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Merge custom settings of xterm (note that this needs the package
# xorg-xrdb)
xrdb -merge ~/.xresources

# Execute i3 as window manager at startup
exec i3

# Execute awesome as window manager at startup
# exec awesome
